volumes:
    sqlite:
        external: true
        name: luk4s.dev.sqlite

services:
    web:
        image: luk4s.dev
        environment:
            - APP_DB=./db/sqlite.db
            - ADMIN_PASSWORD=admin
        ports: ["3000:3000"]
        volumes: ["sqlite:/opt/luk4s.dev/db"]
